export const storeProducts = [
  {
    id: 1,
    title: "Mercedes c 2023",
    img: "img/c2023.jpg",
    price: 215000,
    company: "Mercedes",
    info: "The Mercedes-Benz C-Class 2023 is a luxury sedan that offers a perfect blend of comfort, performance, and advanced technology. The car's exterior design is sleek and modern, with smooth lines and a sporty profile. The interior is spacious and luxurious, with high-quality materials and state-of-the-art technology, including a large infotainment screen, touch controls, and voice commands.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Mercedes c220",
    img: "img/c220.jpg",
    price: 198000,
    company: "Mercedes",
    info: "The Mercedes-Benz C220 is a variant of the C-Class model that offers a balance of performance and fuel efficiency. The car features a 2.0-liter four-cylinder engine that delivers up to 201 horsepower and 369 lb-ft of torque, paired with a nine-speed automatic transmission.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Mercedes e 2023",
    img: "img/e2023.jpg",
    price: 212000,
    company: "Mercedes",
    info: "The Mercedes-Benz E-Class 2023 is a midsize luxury sedan that offers a blend of performance, comfort, and advanced technology. The car's exterior is sleek and elegant, with smooth lines and a modern design that exudes sophistication. The interior is spacious and luxurious, with high-quality materials, comfortable seats, and a range of advanced technology features.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Mercedes c 180 ",
    img: "img/m1-c180.png",
    price: 175000,
    company: "Mercedes",
    info: "The Mercedes-Benz C180 is a compact luxury sedan that offers a balance of comfort, style, and performance. The car features a 1.5-liter four-cylinder turbocharged engine that delivers up to 168 horsepower and 184 lb-ft of torque, paired with a nine-speed automatic transmission.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Mercedes EQE",
    img: "img/eqe.jpg",
    price: 185000,
    company: "Mercedes",
    info: "The Mercedes-Benz EQE is an all-electric luxury sedan that combines the latest in electric powertrain technology with advanced luxury and comfort features. The car features a dual-motor electric powertrain that delivers up to 402 horsepower and 561 lb-ft of torque, with a range of up to 410 miles on a single charge.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Mercedes a 200",
    img: "img/a200.jpg",
    price: 95000,
    company: "Mercedes",
    info: "The Mercedes-Benz A200 is a compact luxury hatchback that offers a balance of performance, comfort, and advanced technology. The car features a 1.3-liter four-cylinder turbocharged engine that delivers up to 161 horsepower and 184 lb-ft of torque, paired with a seven-speed dual-clutch automatic transmission.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Mercedes c 2023",
    img: "img/c2023.jpg",
    price: 210000,
    company: "Mercedes",
    info: "The Mercedes-Benz C-Class 2023 is a compact luxury sedan that offers a blend of performance, comfort, and advanced technology. The car features a 2.0-liter four-cylinder turbocharged engine that delivers up to 255 horsepower and 295 lb-ft of torque, paired with a nine-speed automatic transmission.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Mercedes glc",
    img: "img/glc.jpg",
    price: 160000,
    company: "Mercedes",
    info: "The Mercedes-Benz GLC is a luxury compact SUV that offers a balance of performance, comfort, and advanced technology. The car features a range of engine options, including a 2.0-liter four-cylinder turbocharged engine that delivers up to 255 horsepower and 273 lb-ft of torque, and a 3.0-liter V6 turbocharged engine that delivers up to 385 horsepower and 384 lb-ft of torque.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Google Pixel - Black",
  img: "img/product-1.png",
  price: 10,
  company: "google",
  info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
  inCart: false,
  count: 0,
  total: 0,
};
